### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/wallet-provider#3]
Parallel to issue #2. `react-toastify` has been removed and replace with simply console logging these events.

## Whats needed.

- a more robust logging library that will allow for formatting and possibly even analytics if necessary. This shoudl definately be discussed before moving forward with any particular logging. 

- I have also seen that if we choose a more custom route for taking care of logging within our apps this should be part of our `@decent-dao` package library as a installable logging package.

**Comment by Da-Colon** [comment]
@dannydecent - totally a bucket to be kicked down the road but discussion can only be started. This would require input from you at some point to define product needs for this kinda implementation

**Comment by dannydecent** [comment]
bringing @adamgall into this. by end of next week Id like there to be a solution found and implemented  

current stand out option is https://sentry.io/welcome/

requirements doc started here - https://www.notion.so/Logging-412bdb889db345ab8ad7b0b4d87136d7

**Comment by dannydecent** [comment]
can/should we build our own

**Comment by Da-Colon** [comment]
@adamgall Yessir you are correct. I was leaning more for formatting for this particular card and raising the question of analytics but I agree with your statement on the `ethos`.

**Comment by dannydecent** [comment]
i got ahead of myself on both comments.

yes i agree with the ethos as well. but i would like to be capturing user data - interactions, informational - where it makes sense. here with the npm, no. 

and building our own logger, too aggressive random thought

**Comment by adamgall** [comment]
I'm still a bit confused @Da-Colon.

Formatting, what? Console logging? That the NPM package produces? Honestly I don't think this NPM package should produce _any_ logs in the consuming app. I think it's real rude if an NPM package pollutes my console lol.

Or are you referring to the general way that "messages" ("logs"?) get passed from this NPM module to the client app, that the client app will want to know about (for example: "account changed", "account disconnected", "network changed", etc)?

Or are you referring to what @dannydecent brought up: doing more analytics-based logging, so that "we" (Decent) can see how people are using this package? (I don't like this idea).

Or are you referring to doing analytics-based logging but doing that _on behalf_ of clients, so that, for example, a client developer could easily pass in their own Sentry API key into this `wallet-provider`, so that they can get better insights into how their own users are using the wallet capabilities in their own app?

**Comment by Da-Colon** [comment]
@adamgall you are correct I was speaking to a logging library to 'format/style' logs to the console. But you are right with your next point that we shouldn't be putting our logs into anyones consoles. 

As far as setting up with Sentry to allow for it if a user wants. maybe a thing for the future but this could also be alcomplished by using the events emitted from the package.

Thank you for this discussion. Clarifies what needs to be done here for this card.
- [ ] remove the console logging currently implemented in the apps.
- implement #2 a leave it up to the app to use the events how they see fit.
